"use strict";
const { Router } = require("express");
const { check } = require("express-validator");
const { userGet, userPut, userPost, userDelete } = require("../controllers/user");
const router = Router();
router.get("/", userGet);
router.put("/:id", userPut);
router.post("/", userPost);
router.delete("/", userDelete);
module.exports = router;
